#!/bin/bash
# All files in this package is subject to the GPL v2 license
# More information is in the COPYING file in the top directory of this package.
# Copyright (C) 2011 Severalnines

VERSION=0.2
TEMP=`getopt -o h,H:,p:,P: --long help,host:,password:,port: -n 's9s_cluster_status' -- "$@"`
eval set -- "$TEMP"

while true ; do
  case "$1" in
    -h|--help) help="1" ; shift ;;
    -H|--host) cmon_db_host="$2" ; shift 2 ;;
    -p|--password) cmon_db_password="$2" ; shift 2 ;;
    -P|--port) cmon_db_port="$2" ; shift 2 ;;
    --) shift ; break ;;
    *) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
  esac
done

# Help menu
if [ ! -z "$help" ]; then
	echo "Plugin  : Check Database Cluster Status (Nagios)"
	echo "Version : $VERSION"
	echo "Author  : Severalnines"
	echo ""
	echo "Usage   : `basename $0` -H [host] -p [cmon_password] [options]"
	echo ""
	echo "-H, --host      : ClusterControl/cmon IP address"
	echo "-p, --password  : DB password for user cmon"
	echo "-P, --port      : MySQL port for the host (default 3306)"
	echo "-h, --help      : Print help"
	echo ""
	echo "Example: `basename $0` -H 127.0.0.1 -p 'password'"
	echo ""
	exit 1
fi

[ -z $cmon_db_port ] && cmon_db_port=3306

if [ -z "$cmon_db_host" ] || [ -z "$cmon_db_password" ]; then
	echo "Please specify cmon host and user DB password. Use --help for more info."
	exit 1
fi

# SQL query
query='SELECT status FROM cmon.cluster_state WHERE id=1'

# MySQL client
mysqlbin=`which mysql`
if [ ! -z "$mysqlbin" ]; then
        execute_query=`$mysqlbin -h$cmon_db_host -ucmon -p$cmon_db_password -P$cmon_db_port -A -Bse "$query"`
	if [ ! $execute_query ]; then
	        echo "Failed to query cmon database. The following query failed : $query"
		echo "Unknown: Cluster status is UNKNOWN"
	        stateid=3
		exit $stateid
	else
		clustate=${execute_query^^}
	fi
else
        echo "MySQL client not found. Kindly add the MySQL client into PATH or install MySQL client package"
        exit 1
fi

if (( "$clustate" == "STARTED" )); then
        echo "OK: Cluster status is OK"
        stateid=0
elif  (( "$clustate" == "CRITICAL" || "$clustate" == "UNKNOWN" || "$clustate" == "FAILURE" || "$clustate" == "STOPPED" || "$clustate" == "SHUTTING_DOWN" )); then
        echo "Critical: Cluster status is $clustate"
        stateid=2
else
        echo "Warning: Cluster status is $clustate"
        stateid=1
fi

exit $stateid

