#!/bin/bash

VERSION=0.2
# MySQL client
mysqlbin=`which mysql`

TEMP=`getopt -o H:,p:,P:,h,v --long host:,password:,port:,help,version -n 's9s_cluster_status' -- "$@"`
eval set -- "$TEMP"

while true ; do
  case "$1" in
    -H|--host) cmon_db_host="$2" ; shift 2 ;;
    -p|--password) cmon_db_password="$2" ; shift 2 ;;
    -P|--port) cmon_db_port="$2" ; shift 2 ;;
    -h|--help) help="1" ; shift ;;
    -v|--version) version="1" ; shift ;;
    --) shift ; break ;;
    *) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
  esac
done

printVersion(){
        echo "Plugin  : Check Database Cluster Status (Nagios)"
        echo "Version : $VERSION"
        echo "Author  : Severalnines"
        echo ""
}

helpMenu(){
        echo "Usage   : `basename $0` -H [host] -p [cmon_password] [options]"
        echo ""
        echo "-H, --host      : ClusterControl/cmon IP address"
        echo "-p, --password  : DB password for user cmon"
        echo "-P, --port      : MySQL port for the host (default 3306)"
        echo "-h, --help      : Print help"
        echo ""
        echo "Example: `basename $0` -H 127.0.0.1 -p 'password'"
        echo ""
}

if [ ! -z "$version" ]; then
	printVersion
	exit 0
fi

# Help menu
if [ ! -z "$help" ]; then
	printVersion
	helpMenu
	exit 0
fi

[ -z $cmon_db_port ] && cmon_db_port=3306

if [ -z "$cmon_db_host" ] || [ -z "$cmon_db_password" ]; then
	echo ""
        helpMenu
	exit 1
fi

# SQL query
query='SELECT status FROM cmon.cluster_state WHERE id=1'


if [ ! -z "$mysqlbin" ]; then
        execute_query=`$mysqlbin -h$cmon_db_host -ucmon -p$cmon_db_password -P$cmon_db_port -A -Bse "$query"`
	if [ ! $execute_query ]; then
	        echo "Failed to query cmon database. The following query failed : $query"
		echo "Unknown: Cluster status is UNKNOWN"
	        stateid=3
		exit $stateid
	else
		clustate=${execute_query^^}
	fi
else
        echo "MySQL client not found. Kindly add the MySQL client into PATH or install MySQL client package"
	echo "or change and specify the full path to the mysql client (in the beginning of this file): "
	echo "mysqlbin=`which mysql`"
	echo "to:"
	echo "mysqlbin=/path/to/mysql"
        exit 1
fi

if [ "$clustate" == "STARTED" ]; then
        echo "OK: Cluster status is STARTED"
        stateid=0
elif  [ "$clustate" == "CRITICAL" ] || [ "$clustate" == "FAILURE" ] || [ "$clustate" == "STOPPED" ] || [ "$clustate" == "SHUTTING_DOWN" ]; then
        echo "Critical: Cluster status is $clustate"
        stateid=2
else
        echo "Warning: Cluster status is $clustate"
        stateid=1
fi

exit $stateid

