#!/bin/bash
#
# All files in this package is subject to the GPL v2 license
# More information is in the COPYING file in the top directory of this package.
# Copyright (C) 2011-2017 severalnines.com
#

function ensure_wget_installed
{
    command -v wget &>/dev/null
    [[ $? -eq 0 ]] && return
    echo "=> Installing wget ..."
    if command -v apt-get &>/dev/null; then
        apt-get install -y wget
    else
        yum install -yt wget
    fi
}

function ensure_tools_installed
{
    echo "=> Install/upgrade s9s-tools for error-reporting."
    # make sure we have wget
    ensure_wget_installed
    wget -qO install-s9s-tools.sh http://repo.severalnines.com/s9s-tools/install-s9s-tools.sh
    chmod a+rx install-s9s-tools.sh
    bash install-s9s-tools.sh
    # and lets print out the version to verify
    s9s --version
}

function create_report
{
    ## call s9s tool here to create the report
    unset cmon_user
    if [ -r ~/.s9s/s9s.conf ]; then
	    source ~/.s9s/s9s.conf &>/dev/null
    fi

    # check if s9s.conf doesn't have a user configured, then create one
    if [ -z "$cmon_user" ]; then
	    if [ -z "$SUDO_USER" ]; then
	        cmon_user='root'
	    else
	        cmon_user=$SUDO_USER
	    fi
        s9s user --create --generate-key --controller="https://localhost:9501" --cmon-user="$cmon_user"
        #chown $cmon_user /var/lib/cmon/usermgmt.fifo
        chown $cmon_user ~/.s9s/s9s.conf
    fi

    if [ -n "$DESTINATION" ]; then
        s9s cluster --create-report --output-dir=$savedir --cluster-id=$CLUSTER_ID --log
    else
        s9s cluster --create-report --cluster-id=$CLUSTER_ID --log
    fi

}

WWWSTORE=0

args=`getopt i:d: $*`
set -- $args
for i
do
    case "$i" in
        -i)
            CLUSTER_ID="$2"; shift;
            shift;;
        -d)
            DESTINATION="$2"; shift;
            shift;;
        --)
            shift; break;;
    esac
done

if [ -z "$CLUSTER_ID" ]; then
    echo "s9s_error_report -i <clusterid> [-d destination-dir]"
    exit 1
fi

# We need root access to be able to iterate files inside /etc/cmon.d
if (( EUID != 0 )); then
    echo "must be executed as 'root' or with 'sudo'  ( you are logged in as $USER )."
    exit 1
fi

ensure_tools_installed
create_report

